import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/features/ActiveLink/ActiveLink";
import { type Layout } from "@/types/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Layout) {
	return (
		<html lang="pl">
			<body className={`${inter.className} flex h-0 min-h-screen flex-col`}>
				<nav className="w-full border-b border-neutral-300 bg-neutral-100 py-4">
					<ul className="mx-auto flex w-fit gap-6">
						<li>
							<ActiveLink href={"/"} exact={true}>
								Home
							</ActiveLink>
						</li>
						<li>
							<ActiveLink href={"/products"} exact={false}>
								All
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<div className="flex-grow">{children}</div>
				<footer className="w-full border-t border-neutral-300 bg-neutral-100 py-4 text-center">
					©2023
				</footer>
			</body>
		</html>
	);
}
